<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="L Thomas" />

<meta name="date" content="2023-06-27" />

<title>Use of MCDS.exe alternative optimization engine in Distance and mcds packages</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">

div.csl-bib-body { }
div.csl-entry {
clear: both;
}
.hanging div.csl-entry {
margin-left:2em;
text-indent:-2em;
}
div.csl-left-margin {
min-width:2em;
float:left;
}
div.csl-right-inline {
margin-left:2em;
padding-left:1em;
}
div.csl-indent {
margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Use of MCDS.exe alternative optimization
engine in Distance and mcds packages</h1>
<h4 class="author">L Thomas</h4>
<h4 class="date">27 June 2023</h4>



<p>Here we demonstrate the use of the alternative optimization
<code>mcds.exe</code> in the <code>Distance</code> and <code>mrds</code>
packages.</p>
<p>This vignette requires the packages <code>Distance</code> version
1.0.8 or later and <code>mrds 2.3.0</code> or later. It is designed for
use in the Microsoft Windows operating system – the
<code>mcds.exe</code> engine is not currently supported in MacOS or
Linux.</p>
<div id="objectives" class="section level1">
<h1>Objectives</h1>
<ul>
<li>Download the mcds.exe optimization engine</li>
<li>Demonstrate its use in a simple line transect example via the
<code>Distance</code> package</li>
<li>Demonstrate the same example via the <code>mrds</code> package</li>
<li>Demonstrate its use in a more complex camera trap example via the
`Distance package</li>
</ul>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The <code>Distance</code> package is designed to provide a simple way
to fit detection functions and estimate abundance using conventional
distance sampling methodology (i.e., single observer distance sampling,
possibly with covariates, as described by <span class="citation">(Buckland, Rexstad, Marques, &amp; Oedekoven,
2015)</span>). The main function is <code>ds</code>. Underlying
<code>Distance</code> is the package <code>mrds</code>: when the
function <code>ds</code> is called it does some pre-processing and then
calls the function <code>ddf</code> in the <code>mrds</code> package to
do the work of detection function fitting. <code>mrds</code> uses
maximum likelihood to fit the specified detection function model to the
distance data using a built-in algorithm written in <code>R</code>.</p>
<p>An alternative method for analyzing distance sampling data is using
the Distance for Windows software <span class="citation">(Thomas et al.,
2010)</span>. This software also uses maximum liklihood to fit the
detection function models, and relies on software written in the
programming language FORTRAN to do the fitting. The filename of this
software is <code>MCDS.exe</code>.</p>
<p>In a perfect world, both methods would produce identical results
given the same data and model specification, since the likelihood has
only one maximum. However, the likelihood surface is sometimes complex,
especially when monotonicity constraints are used (which ensure the
estimated detection probability is flat or decreasing with increasing
distance) or with <code>overdispersed&#39;&#39; or</code>spiked’’ data (see
Figure 2 in <span class="citation">(Thomas et al., 2010)</span>), and so
in some (rare) cases one or other piece of software fails to find the
maximum. To counteract this, it is possible to run both the
<code>R</code>-based optimizer and <code>MCDS.exe</code> from the
<code>ds</code> function within the <code>Distance</code> package or the
<code>ddf</code> function within <code>mrds</code> package.</p>
<p>Another motivation for using the <code>MCDS.exe</code> software from
within <code>R</code> is that the <code>R</code>-based optimizer is
sometimes slow to converge and so using <code>MCDS.exe</code> in place
of the <code>R</code>-based optimizer can save significant time,
particularly when doing a nonparametric bootstrap for large
datasets.</p>
<p>This vignette demonstrates how to download and then use the MCDS.exe
sofware from within the <code>Distance</code> and <code>mrds</code>
packages. For more information, see the <code>MCDS.exe</code> help page
within the <code>mrds</code> package.</p>
</div>
<div id="downloading-and-verifying-mcds.exe" class="section level1">
<h1>Downloading and verifying MCDS.exe</h1>
<p>The program <code>MCDS.exe</code> does not come automatically with
the <code>Distance</code> or <code>mrds</code> packages, to avoid
violating CRAN rules, so you must first download it from the distance
sampling website. You can check whether <code>MCDS.exe</code> is
installed already or not by loading the <code>Distance</code>
library:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(Distance)</span></code></pre></div>
<pre><code>## Loading required package: mrds</code></pre>
<pre><code>## This is mrds 2.2.8.9006
## Built: R 4.2.3; ; 2023-06-26 21:44:57 UTC; windows
## MCDS.exe detected, by default single observer analyses will utilise both the mrds R optimiser and the MCDS.exe fortran optimiser to achieve the best fit. See ?ddf and ?MCDS for details.</code></pre>
<pre><code>## 
## Attaching package: &#39;Distance&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:mrds&#39;:
## 
##     create.bins</code></pre>
<p>If <code>MCDS.exe</code> is not installed, then you will receive the
message
<code>MCDS.exe not detected, single observer analyses will only be run using optimiser in mrds R library. See ?MCDS for details.</code></p>
<p>In this case, you need to download it from the Distancesampling.org
web site:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co">#download.file(&quot;http://distancesampling.org/R/MCDS.exe&quot;, paste0(system.file(package=&quot;mrds&quot;),&quot;/MCDS.exe&quot;), mode = &quot;wb&quot;)</span></span></code></pre></div>
<p>Now if you reload the Distance package, the
<code>MCDS.exe not detected</code> message should not be shown:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">detach</span>(<span class="st">&quot;package:Distance&quot;</span>, <span class="at">unload =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a><span class="fu">library</span>(Distance)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;Distance&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:mrds&#39;:
## 
##     create.bins</code></pre>
<p>Now that this software is available, both it and the <code>R</code>
optimizer will be used by default for each analysis; you can also choose
to use just one or the other, as shown below.</p>
</div>
<div id="analysis-using-r-based-optimizer-and-mcds.exe---golf-tee-data" class="section level1">
<h1>Analysis using R-based optimizer and MCDS.exe - Golf Tee data</h1>
<p>This example (of golf tee data, using only observer 1) is taken from
the <code>R</code> help for the <code>ds</code> function:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">data</span>(book.tee.data)</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>tee.data <span class="ot">&lt;-</span> <span class="fu">subset</span>(book.tee.data<span class="sc">$</span>book.tee.dataframe, observer<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>ds.model <span class="ot">&lt;-</span> <span class="fu">ds</span>(tee.data, <span class="at">truncation =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## Starting AIC adjustment term selection.</code></pre>
<pre><code>## Fitting half-normal key function</code></pre>
<pre><code>## ** Warning: One or more cluster sizes are coded as -1. Distance assumes -1 to mean a cluster of undetermined size. These observations are used for estimating detection probability and encounter rate, but not cluster size. **</code></pre>
<pre><code>## AIC= 311.138</code></pre>
<pre><code>## Fitting half-normal key function with cosine(2) adjustments</code></pre>
<pre><code>## ** Warning: One or more cluster sizes are coded as -1. Distance assumes -1 to mean a cluster of undetermined size. These observations are used for estimating detection probability and encounter rate, but not cluster size. **</code></pre>
<pre><code>## AIC= 313.124</code></pre>
<pre><code>## 
## Half-normal key function selected.</code></pre>
<pre><code>## No survey area information supplied, only estimating detection function.</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">summary</span>(ds.model)</span></code></pre></div>
<pre><code>## 
## Summary for distance analysis 
## Number of observations :  124 
## Distance range         :  0  -  4 
## 
## Model       : Half-normal key function 
## AIC         :  311.1385 
## Optimisation:  mrds (nlminb) 
## 
## Detection function parameters
## Scale coefficient(s):  
##              estimate         se
## (Intercept) 0.6632435 0.09981249
## 
##                        Estimate          SE         CV
## Average p             0.5842744  0.04637627 0.07937412
## N in covered region 212.2290462 20.85130344 0.09824906</code></pre>
<p>Assuming you have <code>MCDS.exe</code> installed, the default is
that both it and the <code>R</code>-based optimizer are run. Both give
the same result in this example, and when this happens the result from
the <code>R</code>-based optimizer is used. You can see this from the
line of summary output:</p>
<p><code>Optimisation:  mrds (nlminb)</code></p>
<p>where <code>mrds</code> is the <code>R</code> package that the
<code>Distance</code> package relies on, and <code>nlminb</code> is the
<code>R</code>-based optimizer.</p>
<p>You can see both optimizers in action by setting the
<code>debug_level</code> argument of the <code>ds</code> function:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>ds.model <span class="ot">&lt;-</span> <span class="fu">ds</span>(tee.data, <span class="at">truncation =</span> <span class="dv">4</span>, <span class="at">debug_level =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Starting AIC adjustment term selection.</code></pre>
<pre><code>## Fitting half-normal key function</code></pre>
<pre><code>## DEBUG: initial values = -0.1031529</code></pre>
<pre><code>## Running MCDS.exe...</code></pre>
<pre><code>## Command file written to C:\Users\lt5\AppData\Local\Temp\RtmpaAx2xR\cmdtmp17c872004ef.txt</code></pre>
<pre><code>## Stats file written to C:\Users\lt5\AppData\Local\Temp\RtmpaAx2xR\stat17c846b34649.txt</code></pre>
<pre><code>## ** Warning: One or more cluster sizes are coded as -1. Distance assumes -1 to mean a cluster of undetermined size. These observations are used for estimating detection probability and encounter rate, but not cluster size. **</code></pre>
<pre><code>## DEBUG: initial values = 0.6632378 
## 
## DEBUG: Convergence! 
##        Iteration  0.0 
##        Converge   = 0 
##        nll        = 154.5692 
##        parameters = 0.6632378</code></pre>
<pre><code>## MCDS.exe log likehood: -154.5697</code></pre>
<pre><code>## MCDS.exe pars: 1.941067</code></pre>
<pre><code>## mrds refitted log likehood: -154.5692276</code></pre>
<pre><code>## mrds refitted pars: 0.6632378</code></pre>
<pre><code>## 
## DEBUG: Convergence! 
##        Iteration  0.0 
##        Converge   = 0 
##        nll        = 154.5692 
##        parameters = 0.6632435</code></pre>
<pre><code>## AIC= 311.138</code></pre>
<pre><code>## Fitting half-normal key function with cosine(2) adjustments</code></pre>
<pre><code>## DEBUG: initial values = -0.1031529 0</code></pre>
<pre><code>## Running MCDS.exe...</code></pre>
<pre><code>## Command file written to C:\Users\lt5\AppData\Local\Temp\RtmpaAx2xR\cmdtmp17c816c0106d.txt</code></pre>
<pre><code>## Stats file written to C:\Users\lt5\AppData\Local\Temp\RtmpaAx2xR\stat17c872115c1.txt</code></pre>
<pre><code>## ** Warning: One or more cluster sizes are coded as -1. Distance assumes -1 to mean a cluster of undetermined size. These observations are used for estimating detection probability and encounter rate, but not cluster size. **</code></pre>
<pre><code>## DEBUG: initial values = 0.6606793 -0.0159333 
## 
## DEBUG: Convergence! 
##        Iteration  0.0 
##        Converge   = 0 
##        nll        = 154.5619 
##        parameters = 0.6606793, -0.0159333</code></pre>
<pre><code>## MCDS.exe log likehood: -154.5624</code></pre>
<pre><code>## MCDS.exe pars: 1.936107, -0.0159333</code></pre>
<pre><code>## mrds refitted log likehood: -154.5619307</code></pre>
<pre><code>## mrds refitted pars: 0.6606793, -0.0159333</code></pre>
<pre><code>## 
## Iter: 1 fn: 154.5619  Pars:   0.66068 -0.01591
## Iter: 2 fn: 154.5619  Pars:   0.66069 -0.01592
## solnp--&gt; Completed in 2 iterations
## 
## DEBUG: Convergence! 
##        Iteration  0.0 
##        Converge   = 0 
##        nll        = 154.5619 
##        parameters = 0.6606853, -0.0159233</code></pre>
<pre><code>## AIC= 313.124</code></pre>
<pre><code>## 
## Half-normal key function selected.</code></pre>
<pre><code>## No survey area information supplied, only estimating detection function.</code></pre>
<p>First the half-normal with 0 adjustments is run, and for this model
the <code>MCDS.exe</code> sofware is run first, followed by the
<code>R</code>-based (<code>mrds</code>) optimizer. Both converge and
both give the same <code>nll</code> (negative log-likelihood) or
154.5692, giving an AIC of 311.138. The model with half-normal and a
cosine adjustment of order 2 is then fitted to the data, with first the
<code>MCDS.exe</code> optimizer and then the <code>R</code>-based
optimizer. Again both give the same result of nll 154.5619 and an AIC of
313.124. This is higher than the AIC with no adjustments so half-normal
with no adjustments is chosen.</p>
<p>In this case, both optimizers produced the same result, so there is
no benefit to run <code>MCDS.exe</code>. Our tests have shown that in
general</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-buckland2015distance" class="csl-entry">
Buckland, S., Rexstad, E., Marques, T., &amp; Oedekoven, C. (2015).
<em>Distance sampling: Methods and applications</em>. Springer.
</div>
<div id="ref-Thomas2010" class="csl-entry">
Thomas, L., Buckland, S. T., Rexstad, E. A., Laake, J. L., Strindberg,
S., Hedley, S. L., … Marques, T. A. (2010). Distance software: Design
and analysis of distance sampling surveys for estimating population
size. <em>Journal of Applied Ecology</em>, <em>47</em>, 5–14. <a href="https://doi.org/110.1111/j.1365-2664.2009.01737.x">https://doi.org/110.1111/j.1365-2664.2009.01737.x</a>
</div>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
